apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.authService.dbName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: auth-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: auth-db-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
