apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
# Values are base64 encoded
# echo -n "postgres" | base64  →  cG9zdGdyZXM=
# echo -n "404E635266..." | base64  →  (jwt secret)
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
