apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: product-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "product_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: product-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: product-db-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: product-db-service
  namespace: ecommerce
spec:
  selector:
    app: product-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
